name: emscripten-shared
run-name: emscripten-shared
on: [push]
jobs:
  conan-create:
    uses: ./.github/workflows/main.yml
    with:
        runs-on: ubuntu-latest
        conan-options: -o skia/*:shared=True -pr:h=./profiles/emscripten.profile

