name: emscripten-static
run-name: emscripten-static
on: [push]
jobs:
  conan-create:
    uses: ./.github/workflows/main.yml
    with:
        runs-on: ubuntu-latest
        conan-options: -o skia/*:shared=False -pr:h=./profiles/emscripten.profile

