name: ios-armv8-static
run-name: ios-armv8-static
on: [push]
jobs:
  conan-create:
    uses: ./.github/workflows/main.yml
    with:
        runs-on: macos-latest
        conan-options: -o skia/*:shared=False -pr:h=./profiles/ios-armv8.profile
