name: ubuntu-latest-shared
run-name: ubuntu-latest-shared
on: [push]
jobs:
  conan-create:
    uses: ./.github/workflows/main.yml
    with:
        runs-on: ubuntu-latest
        conan-options: -o skia/*:shared=True
